//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int CartDetailID { get; set; }
        public int CartID { get; set; }
        public string ClothesID { get; set; }
        public string ClothesName { get; set; }
        public string MainImage { get; set; }
        public string SizeName { get; set; }
        public string ColorID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
