//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_ClothingType
    {
        public string CateCloTypeName { get; set; }
        public string CategoryID { get; set; }
        public string ClothingTypeID { get; set; }
        public string Img { get; set; }
        public string UrlImg { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ClothingType ClothingType { get; set; }
    }
}
