//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cloth()
        {
            this.Clothes_Color_Size = new HashSet<Clothes_Color_Size>();
            this.Images = new HashSet<Image>();
        }
    
        public string ClothesID { get; set; }
        public string ClothesName { get; set; }
        public string MainImage { get; set; }
        public string UrlImage { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public string Description { get; set; }
        public string Fabric { get; set; }
        public string UserInstructions { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CategoryID { get; set; }
        public string ClothingTypeID { get; set; }
        public string ClothingStyleID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ClothingType ClothingType { get; set; }
        public virtual ClothingStyle ClothingStyle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clothes_Color_Size> Clothes_Color_Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
