//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothes_Color_Size
    {
        public string ClothesID { get; set; }
        public string ColorID { get; set; }
        public string SizeID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual Color Color { get; set; }
        public virtual Size Size { get; set; }
    }
}
